[package]
name = "unicode_segmentation_cffi"
version = "0.1.0"
build = "build.rs"

[lib]
name = "unicode_segmentation_cffi"
crate-type = ["cdylib"]

[dependencies]
unicode-segmentation = "1.6.0"
itertools = "0.9.0"

[build-dependencies]
cbindgen = "0.13.1"
